Newsweek homepage responsive clone
AlanSoto31/Newsweek-Responsive-Clone pull request #2
Opened 2020-09-22 18:12 UTC by AlanSoto31

It is a clone from Newsweek home page but including fully responsive design. One very important requisite for this project was the use of bootstrap as more as possible, which was a great opportunity to learn how this usefull tool works. It was built from mobile-size to xl-size. The most responsive design happens inside the following ranges 320px 768px 1024px 1044px.

2020-09-22 20:06 UTC, jubaan requested changes
# Status: Changes Required :recycle:

## :wave: :wave: :wave: Hello Team!! Great work on the project!!

It looks really close to the original! Excelent job Team! :clap: :clap:

:100: Great Pull Request and Commit Messages
:100: Descriptive enough README
:100: Clone Very similar to the original

## Required Changes
### [Mandatory] :red_circle: 

- [x] menu doesn't resize properly on bigger screens (1440)
![image](https://user-images.githubusercontent.com/25774518/93926891-ba318180-fcdd-11ea-9ce0-c0b90987d476.png)

- [ ] navbar is not sticky
![image](https://user-images.githubusercontent.com/25774518/93927114-0b417580-fcde-11ea-9908-0e33231994be.png)

- [x] Search is not vertical centered
![image](https://user-images.githubusercontent.com/25774518/93928050-5740ea00-fcdf-11ea-8bd2-9e830d8e3ff0.png)

- [x] More stories is not displaying properly
![image](https://user-images.githubusercontent.com/25774518/93928148-7dff2080-fcdf-11ea-985a-2a4c76cf5812.png)

- [x] Sign up form Is not displaying properly.
![image](https://user-images.githubusercontent.com/25774518/93928246-9e2edf80-fcdf-11ea-982b-98e8843bae38.png)

- [x] Columns width causing trouble with elements. See images above.

- [x] Sports section not displaying properly on tablet (768)
![image](https://user-images.githubusercontent.com/25774518/93929113-f74b4300-fce0-11ea-9555-d5c1d4ce389c.png)

- [x] White margin on mobile version (320)
![image](https://user-images.githubusercontent.com/25774518/93929179-18ac2f00-fce1-11ea-8a60-3201cf013c73.png)

- [x] Sign up section not displaying properly on mobile
![image](https://user-images.githubusercontent.com/25774518/93929351-59a44380-fce1-11ea-972e-92eb8a3d60b9.png)

- [ ] Sports section not displaying properly on mobile
![image](https://user-images.githubusercontent.com/25774518/93929512-9a03c180-fce1-11ea-8180-8d3280333078.png)

- [ ] Use semantic HTML for ```header``` and ```main```

### [OPTIONAL] :large_blue_circle: 

- [ ] Assign the ```style.css``` to it's own folder. Create a directory structure similar to this.
```
/   css/
        style.css
    img/
        some_images.jpg
    js/
        some_javascript.js
    index.html
```

- [ ] Move the ```style.css``` below the Boostrap CDN. This way makes it easier to overide Bootstrap css and use a custom stylesheet.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-22 20:08 UTC, jubaan requested changes

2020-09-22 20:08 UTC, jubaan commented on index.html
> +    <div class="body">
- [ ] Wrap ```navbar``` around ```header``` semantic html tag. Body wrapper seems unnecesary if the code uses semantic html.

2020-09-22 23:57 UTC, umairarshadbutt commented
##
## Pull Request under review by Umair Arshad (TSE)

2020-09-23 00:14 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @AlanSoto31 AND @NataJenkins 

Good job with the changes! :tada: We are almost there.
We, however, do have some few changes to carry out before we proceed (see review comment).

##

 For this project, we have to make sure nothing is messed up. Kindly compare the screenshots below 👇 and work on the suggested changes.
- [x] Remove `!important `from css file. ([Article for support](https://speckyboy.com/good-bad-css-practices/)) ( [screenshot](https://user-images.githubusercontent.com/29689273/93404399-8997b500-f8a3-11ea-8f88-fb12b8f6ca80.png) from Pathwright)
### Navbar
- [ ] Remove hamburger from large screens

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://alansoto31.github.io/Newsweek-Responsive-Clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/93949519-3e294f00-fd5a-11ea-8550-6be8d30da78a.png)|![clone](https://user-images.githubusercontent.com/29689273/93949549-5305e280-fd5a-11ea-877a-f8771899d434.png)|

### Footer
- [x] Remove the padding left

|[Source Page](https://www.newsweek.com/)|[Clone Page](https://alansoto31.github.io/Newsweek-Responsive-Clone/)|
|:---:|:---:|
|![source-page](https://user-images.githubusercontent.com/29689273/93949932-6e252200-fd5b-11ea-8cfa-698c59c7f94e.png)|![clone](https://user-images.githubusercontent.com/29689273/93949948-7b421100-fd5b-11ea-94d7-d70b93a88b17.png)|

##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you stick at any point or have any questions, let me know on slack at any time. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2020-09-23 00:14 UTC, umairarshadbutt commented on styles.css
> +  text-decoration: none !important;
remove `!important`

2020-09-23 00:14 UTC, umairarshadbutt commented on styles.css
> +  text-decoration-color: #f72210 !important;
remove `!important`

2020-09-23 00:14 UTC, umairarshadbutt commented on styles.css
> +    font-size: 14px !important;
remove `!important`

2020-09-23 15:12 UTC, jubaan approved these changes
# Status: Approved :tada: :tada: :tada:

## Congrats team! you've worked on the required changes!!

You may now merge to master.

## :rocket: See you at the top!

### [COMMENTS]

- [ ] I've seen that you minimize the use of ```!important``` in the project CSS. For next projects try the project to use none. While it works and does what is expected, in the long run and bigger websites ```!important``` creates more issues than the one's it solves.

2020-09-23 15:20 UTC, merged